// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIntegrador.EntityFrameWork;

#nullable disable

namespace ProyectoIntegrador.EntityFrameWork.Migrations
{
    [DbContext(typeof(ProyectoDBContext))]
    [Migration("20251105185426_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Comentario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("artesanoId")
                        .HasColumnType("int");

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("artesanoId");

                    b.HasIndex("clienteId");

                    b.HasIndex("productoId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Artesanoid")
                        .HasColumnType("int");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Artesanoid");

                    b.HasIndex("Clienteid");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.LineaFactura", b =>
                {
                    b.Property<int>("idProducto")
                        .HasColumnType("int");

                    b.Property<int>("idFactura")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("precioUnitario")
                        .HasColumnType("int");

                    b.HasKey("idProducto", "idFactura");

                    b.HasIndex("idFactura");

                    b.ToTable("LineaFactura");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.PedidoPersonalizado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("artesanoId")
                        .HasColumnType("int");

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("artesanoId");

                    b.HasIndex("clienteId");

                    b.ToTable("PedidoPersonalizado");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<int>("artesanoid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<int>("subCategroiaId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.HasIndex("artesanoid");

                    b.HasIndex("subCategroiaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.SubCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categoriaId");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            id = 1,
                            TipoUsuario = "Cliente",
                            apellido = "Pérez",
                            nombre = "Juan",
                            password = "juancliente123",
                            rol = "CLIENTE"
                        },
                        new
                        {
                            id = 2,
                            TipoUsuario = "Artesano",
                            apellido = "Gómez",
                            nombre = "Laura",
                            password = "lauraartesana123",
                            rol = "ARTESANO"
                        },
                        new
                        {
                            id = 3,
                            TipoUsuario = "Admin",
                            apellido = "Root",
                            nombre = "Admin",
                            password = "admin123456",
                            rol = "ADMIN"
                        });
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Admin", b =>
                {
                    b.HasBaseType("ProyectoIntegrador.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", b =>
                {
                    b.HasBaseType("ProyectoIntegrador.LogicaNegocio.Entidades.Usuario");

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasIndex("Clienteid");

                    b.HasDiscriminator().HasValue("Artesano");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", b =>
                {
                    b.HasBaseType("ProyectoIntegrador.LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Comentario", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", "artesano")
                        .WithMany()
                        .HasForeignKey("artesanoId");

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId");

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Producto", "producto")
                        .WithMany("comentarios")
                        .HasForeignKey("productoId");

                    b.Navigation("artesano");

                    b.Navigation("cliente");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Factura", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", null)
                        .WithMany("ventas")
                        .HasForeignKey("Artesanoid");

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", "Cliente")
                        .WithMany("compras")
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.LineaFactura", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Factura", "factura")
                        .WithMany("itemsFactura")
                        .HasForeignKey("idFactura")
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("idProducto")
                        .IsRequired();

                    b.Navigation("factura");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.PedidoPersonalizado", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", "artesano")
                        .WithMany()
                        .HasForeignKey("artesanoId");

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId");

                    b.Navigation("artesano");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Producto", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", null)
                        .WithMany("productosFavoritos")
                        .HasForeignKey("Clienteid");

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", "artesano")
                        .WithMany("productos")
                        .HasForeignKey("artesanoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.SubCategoria", "SubCategoria")
                        .WithMany("Productos")
                        .HasForeignKey("subCategroiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubCategoria");

                    b.Navigation("artesano");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.SubCategoria", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Categoria", "categoria")
                        .WithMany("categorias")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.OwnsOne("ProyectoIntegrador.LogicaNegocio.ValueObjects.Email", "email", b1 =>
                        {
                            b1.Property<int>("Usuarioid")
                                .HasColumnType("int");

                            b1.Property<string>("email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("email_email");

                            b1.HasKey("Usuarioid");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("Usuarioid");

                            b1.HasData(
                                new
                                {
                                    Usuarioid = 1,
                                    email = "juan@cliente.com"
                                },
                                new
                                {
                                    Usuarioid = 2,
                                    email = "laura@artesana.com"
                                },
                                new
                                {
                                    Usuarioid = 3,
                                    email = "admin@site.com"
                                });
                        });

                    b.Navigation("email")
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", b =>
                {
                    b.HasOne("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", null)
                        .WithMany("artesanosSeguidos")
                        .HasForeignKey("Clienteid");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", b =>
                {
                    b.OwnsOne("ProyectoIntegrador.LogicaNegocio.ValueObjects.Direccion", "direccion", b1 =>
                        {
                            b1.Property<int>("Clienteid")
                                .HasColumnType("int");

                            b1.Property<string>("barrio")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("direccion_barrio");

                            b1.Property<string>("departamento")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("direccion_departamento");

                            b1.Property<string>("domicilio")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("direccion_domicilio");

                            b1.HasKey("Clienteid");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("Clienteid");

                            b1.HasData(
                                new
                                {
                                    Clienteid = 1,
                                    barrio = "Centro",
                                    departamento = "Montevideo",
                                    domicilio = "Av. Libertad 123"
                                });
                        });

                    b.Navigation("direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Categoria", b =>
                {
                    b.Navigation("categorias");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Factura", b =>
                {
                    b.Navigation("itemsFactura");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Producto", b =>
                {
                    b.Navigation("comentarios");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.SubCategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Artesano", b =>
                {
                    b.Navigation("productos");

                    b.Navigation("ventas");
                });

            modelBuilder.Entity("ProyectoIntegrador.LogicaNegocio.Entidades.Cliente", b =>
                {
                    b.Navigation("artesanosSeguidos");

                    b.Navigation("compras");

                    b.Navigation("productosFavoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
