//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoIntegrador_Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptando pedido....
        /// </summary>
        public static string AceptandoPedido {
            get {
                return ResourceManager.GetString("AceptandoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar encargo.
        /// </summary>
        public static string AceptarEncargo {
            get {
                return ResourceManager.GetString("AceptarEncargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualiza tus datos personales.
        /// </summary>
        public static string ActualizarDatosPersonales {
            get {
                return ResourceManager.GetString("ActualizarDatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar producto.
        /// </summary>
        public static string ActualizarProducto {
            get {
                return ResourceManager.GetString("ActualizarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregados recientemente.
        /// </summary>
        public static string AgregadosRecientemente {
            get {
                return ResourceManager.GetString("AgregadosRecientemente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar a favoritos.
        /// </summary>
        public static string AgregarAFavoritos {
            get {
                return ResourceManager.GetString("AgregarAFavoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al carrito.
        /// </summary>
        public static string AgregarAlCarrito {
            get {
                return ResourceManager.GetString("AgregarAlCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar fotos nuevas.
        /// </summary>
        public static string AgregarFotosNuevas {
            get {
                return ResourceManager.GetString("AgregarFotosNuevas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar producto.
        /// </summary>
        public static string AgregarProducto {
            get {
                return ResourceManager.GetString("AgregarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de producto.
        /// </summary>
        public static string AltaProducto {
            get {
                return ResourceManager.GetString("AltaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artesano.
        /// </summary>
        public static string Artesano {
            get {
                return ResourceManager.GetString("Artesano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artesano reportado.
        /// </summary>
        public static string ArtesanoReportado {
            get {
                return ResourceManager.GetString("ArtesanoReportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este artesano aún no tiene comentarios..
        /// </summary>
        public static string ArtesanoSinComentarios {
            get {
                return ResourceManager.GetString("ArtesanoSinComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este artesano aún no tiene productos publicados..
        /// </summary>
        public static string ArtesanoSinProductos {
            get {
                return ResourceManager.GetString("ArtesanoSinProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artesanos que seguís.
        /// </summary>
        public static string ArtesanosQueSeguis {
            get {
                return ResourceManager.GetString("ArtesanosQueSeguis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos.
        /// </summary>
        public static string Articulos {
            get {
                return ResourceManager.GetString("Articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Barrio.
        /// </summary>
        public static string Barrio {
            get {
                return ResourceManager.GetString("Barrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Barrio o zona.
        /// </summary>
        public static string BarrioZona {
            get {
                return ResourceManager.GetString("BarrioZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar productos.
        /// </summary>
        public static string BuscarProductos {
            get {
                return ResourceManager.GetString("BuscarProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar productos....
        /// </summary>
        public static string BuscarProductosPlaceholder {
            get {
                return ResourceManager.GetString("BuscarProductosPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por título o cliente....
        /// </summary>
        public static string BuscarTituloCliente {
            get {
                return ResourceManager.GetString("BuscarTituloCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar usuarios....
        /// </summary>
        public static string BuscarUsuarios {
            get {
                return ResourceManager.GetString("BuscarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar usuarios....
        /// </summary>
        public static string BuscarUsuariosPlaceholder {
            get {
                return ResourceManager.GetString("BuscarUsuariosPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificar.
        /// </summary>
        public static string Calificar {
            get {
                return ResourceManager.GetString("Calificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle y número.
        /// </summary>
        public static string CalleNumero {
            get {
                return ResourceManager.GetString("CalleNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string CambiarContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar imagen principal.
        /// </summary>
        public static string CambiarImagenPrincipal {
            get {
                return ResourceManager.GetString("CambiarImagenPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad a eliminar.
        /// </summary>
        public static string CantidadEliminar {
            get {
                return ResourceManager.GetString("CantidadEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de productos.
        /// </summary>
        public static string CantidadProductos {
            get {
                return ResourceManager.GetString("CantidadProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad vendida.
        /// </summary>
        public static string CantidadVendida {
            get {
                return ResourceManager.GetString("CantidadVendida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        public static string Catalogo {
            get {
                return ResourceManager.GetString("Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de productos.
        /// </summary>
        public static string CatalogoProductos {
            get {
                return ResourceManager.GetString("CatalogoProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente A–Z.
        /// </summary>
        public static string ClienteAZ {
            get {
                return ResourceManager.GetString("ClienteAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Z–A.
        /// </summary>
        public static string ClienteZA {
            get {
                return ResourceManager.GetString("ClienteZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación.
        /// </summary>
        public static string CodigoVerificacion {
            get {
                return ResourceManager.GetString("CodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completá los datos para registrarte.
        /// </summary>
        public static string CompletarDatosRegistro {
            get {
                return ResourceManager.GetString("CompletarDatosRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compras.
        /// </summary>
        public static string Compras {
            get {
                return ResourceManager.GetString("Compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar la contraseña nueva.
        /// </summary>
        public static string ConfirmarContrasenaNueva {
            get {
                return ResourceManager.GetString("ConfirmarContrasenaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar eliminación.
        /// </summary>
        public static string ConfirmarEliminacion {
            get {
                return ResourceManager.GetString("ConfirmarEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar este producto?.
        /// </summary>
        public static string ConfirmarEliminarProducto {
            get {
                return ResourceManager.GetString("ConfirmarEliminarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar compra.
        /// </summary>
        public static string ContinuarCompra {
            get {
                return ResourceManager.GetString("ContinuarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string ContrasenaActual {
            get {
                return ResourceManager.GetString("ContrasenaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña nueva.
        /// </summary>
        public static string ContrasenaNueva {
            get {
                return ResourceManager.GetString("ContrasenaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu correo fue confirmado con éxito. Ya podés iniciar sesión..
        /// </summary>
        public static string CorreoConfirmado {
            get {
                return ResourceManager.GetString("CorreoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CrearCuenta {
            get {
                return ResourceManager.GetString("CrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear pedido personalizado.
        /// </summary>
        public static string CrearPedidoPersonalizado {
            get {
                return ResourceManager.GetString("CrearPedidoPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta eliminada.
        /// </summary>
        public static string CuentaEliminada {
            get {
                return ResourceManager.GetString("CuentaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu cuenta fue eliminada correctamente.
        /// </summary>
        public static string CuentaEliminadaCorrectamente {
            get {
                return ResourceManager.GetString("CuentaEliminadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard de artesano.
        /// </summary>
        public static string DashboardArtesano {
            get {
                return ResourceManager.GetString("DashboardArtesano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dejar un comentario .
        /// </summary>
        public static string DejarComentario {
            get {
                return ResourceManager.GetString("DejarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dejar de seguir.
        /// </summary>
        public static string DejarDeSeguir {
            get {
                return ResourceManager.GetString("DejarDeSeguir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string Departamento {
            get {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar PDF.
        /// </summary>
        public static string DescargarPDF {
            get {
                return ResourceManager.GetString("DescargarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de la compra.
        /// </summary>
        public static string DetalleCompra {
            get {
                return ResourceManager.GetString("DetalleCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del producto.
        /// </summary>
        public static string DetalleProducto {
            get {
                return ResourceManager.GetString("DetalleProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de la compra.
        /// </summary>
        public static string DetallesCompra {
            get {
                return ResourceManager.GetString("DetallesCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        public static string Domicilio {
            get {
                return ResourceManager.GetString("Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar producto.
        /// </summary>
        public static string EditarProducto {
            get {
                return ResourceManager.GetString("EditarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta .
        /// </summary>
        public static string EliminarCuenta {
            get {
                return ResourceManager.GetString("EliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar producto.
        /// </summary>
        public static string EliminarProducto {
            get {
                return ResourceManager.GetString("EliminarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email verificado.
        /// </summary>
        public static string EmailVerificado {
            get {
                return ResourceManager.GetString("EmailVerificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Email verificado correctamente!.
        /// </summary>
        public static string EmailVerificadoCorrectamente {
            get {
                return ResourceManager.GetString("EmailVerificadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar comentario.
        /// </summary>
        public static string EnviarComentario {
            get {
                return ResourceManager.GetString("EnviarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar pedido.
        /// </summary>
        public static string EnviarPedido {
            get {
                return ResourceManager.GetString("EnviarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar producto.
        /// </summary>
        public static string EnviarReporte {
            get {
                return ResourceManager.GetString("EnviarReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba su comentario.
        /// </summary>
        public static string EscribaComentario {
            get {
                return ResourceManager.GetString("EscribaComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        public static string EstadoPendiente {
            get {
                return ResourceManager.GetString("EstadoPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura no fiiscal.
        /// </summary>
        public static string FacturaNoFiscal {
            get {
                return ResourceManager.GetString("FacturaNoFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta factura no tiene ítems..
        /// </summary>
        public static string FacturaSinItems {
            get {
                return ResourceManager.GetString("FacturaSinItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorito.
        /// </summary>
        public static string Favorito {
            get {
                return ResourceManager.GetString("Favorito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favoritos.
        /// </summary>
        public static string Favoritos {
            get {
                return ResourceManager.GetString("Favoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar pedido.
        /// </summary>
        public static string FinalizarPedido {
            get {
                return ResourceManager.GetString("FinalizarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        public static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de.
        /// </summary>
        public static string FotoDe {
            get {
                return ResourceManager.GetString("FotoDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto por defecto.
        /// </summary>
        public static string FotoPorDefecto {
            get {
                return ResourceManager.GetString("FotoPorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos adicionales (opcional).
        /// </summary>
        public static string FotosAdicionales {
            get {
                return ResourceManager.GetString("FotosAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos secundarias.
        /// </summary>
        public static string FotosSecundarias {
            get {
                return ResourceManager.GetString("FotosSecundarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string GuardarCambios {
            get {
                return ResourceManager.GetString("GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar producto.
        /// </summary>
        public static string GuardarProducto {
            get {
                return ResourceManager.GetString("GuardarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer pedido personalizado.
        /// </summary>
        public static string HacerPedidoPersonalizado {
            get {
                return ResourceManager.GetString("HacerPedidoPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de facturas.
        /// </summary>
        public static string HistorialFacturas {
            get {
                return ResourceManager.GetString("HistorialFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen principal.
        /// </summary>
        public static string ImagenPrincipal {
            get {
                return ResourceManager.GetString("ImagenPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen del producto (principal).
        /// </summary>
        public static string ImagenProductoPrincipal {
            get {
                return ResourceManager.GetString("ImagenProductoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORT Uruguay — Ingeniería.
        /// </summary>
        public static string IngenieriaORT {
            get {
                return ResourceManager.GetString("IngenieriaORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresá el código que enviamos a tu correo para confirmar..
        /// </summary>
        public static string IngresarCodigoCorreo {
            get {
                return ResourceManager.GetString("IngresarCodigoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresá el código que enviamos a tu correo para confirmar.
        /// </summary>
        public static string IngreseCodigoCorreo {
            get {
                return ResourceManager.GetString("IngreseCodigoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresá el código que enviamos a tu correo para confirmar.
        /// </summary>
        public static string IngreseCodigoEliminar {
            get {
                return ResourceManager.GetString("IngreseCodigoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresá tus credenciales para continuar.
        /// </summary>
        public static string IngreseCredenciales {
            get {
                return ResourceManager.GetString("IngreseCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institucional.
        /// </summary>
        public static string Institucional {
            get {
                return ResourceManager.GetString("Institucional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al inicio.
        /// </summary>
        public static string IrAlInicio {
            get {
                return ResourceManager.GetString("IrAlInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más antiguos primero.
        /// </summary>
        public static string MasAntiguos {
            get {
                return ResourceManager.GetString("MasAntiguos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más recientes primero.
        /// </summary>
        public static string MasRecientes {
            get {
                return ResourceManager.GetString("MasRecientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi carrito.
        /// </summary>
        public static string MiCarrito {
            get {
                return ResourceManager.GetString("MiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string MiPerfil {
            get {
                return ResourceManager.GetString("MiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis compras.
        /// </summary>
        public static string MisCompras {
            get {
                return ResourceManager.GetString("MisCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis encargos.
        /// </summary>
        public static string MisEncargos {
            get {
                return ResourceManager.GetString("MisEncargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis favoritos.
        /// </summary>
        public static string MisFavoritos {
            get {
                return ResourceManager.GetString("MisFavoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis productos.
        /// </summary>
        public static string MisProductos {
            get {
                return ResourceManager.GetString("MisProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis ventas.
        /// </summary>
        public static string MisVentas {
            get {
                return ResourceManager.GetString("MisVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Describa el motivo del reporte.
        /// </summary>
        public static string MotivoReporte {
            get {
                return ResourceManager.GetString("MotivoReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay productos registrados aún..
        /// </summary>
        public static string NoHayProductos {
            get {
                return ResourceManager.GetString("NoHayProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay productos para mostrar.
        /// </summary>
        public static string NoHayProductosMostrar {
            get {
                return ResourceManager.GetString("NoHayProductosMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay reportes pendientes.
        /// </summary>
        public static string NoHayReportesPendientes {
            get {
                return ResourceManager.GetString("NoHayReportesPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron productos..
        /// </summary>
        public static string NoSeEncontraronProductos {
            get {
                return ResourceManager.GetString("NoSeEncontraronProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron usuarios..
        /// </summary>
        public static string NoSeEncontraronUsuarios {
            get {
                return ResourceManager.GetString("NoSeEncontraronUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no seguís a ningún artesano.
        /// </summary>
        public static string NoSiguesArtesanos {
            get {
                return ResourceManager.GetString("NoSiguesArtesanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tenés cuenta?.
        /// </summary>
        public static string NoTieneCuenta {
            get {
                return ResourceManager.GetString("NoTieneCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavía no tenés productos favoritos.
        /// </summary>
        public static string NoTieneFavoritos {
            get {
                return ResourceManager.GetString("NoTieneFavoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes productos registrados aún.
        /// </summary>
        public static string NoTieneProductos {
            get {
                return ResourceManager.GetString("NoTieneProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te notificaremos cuando el pago sea confirmado..
        /// </summary>
        public static string NotificacionPagoConfirmado {
            get {
                return ResourceManager.GetString("NotificacionPagoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ventas registradas.
        /// </summary>
        public static string NoVentasRegistradas {
            get {
                return ResourceManager.GetString("NoVentasRegistradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No ves el correo?.
        /// </summary>
        public static string NoVesCorreo {
            get {
                return ResourceManager.GetString("NoVesCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string NuevaContrasena {
            get {
                return ResourceManager.GetString("NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otras opciones....
        /// </summary>
        public static string OtrasOpciones {
            get {
                return ResourceManager.GetString("OtrasOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago en proceso.
        /// </summary>
        public static string PagoEnProceso {
            get {
                return ResourceManager.GetString("PagoEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago fallido.
        /// </summary>
        public static string PagoFallido {
            get {
                return ResourceManager.GetString("PagoFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu pago fue rechazado por Mercado Pago..
        /// </summary>
        public static string PagoRechazado {
            get {
                return ResourceManager.GetString("PagoRechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu pago está siendo validado por Mercado Pago..
        /// </summary>
        public static string PagoValidandose {
            get {
                return ResourceManager.GetString("PagoValidandose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para el artesano.
        /// </summary>
        public static string ParaElArtesano {
            get {
                return ResourceManager.GetString("ParaElArtesano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido finalizado.
        /// </summary>
        public static string PedidoFinalizado {
            get {
                return ResourceManager.GetString("PedidoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido por:.
        /// </summary>
        public static string PedidoPor {
            get {
                return ResourceManager.GetString("PedidoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos personalizados.
        /// </summary>
        public static string PedidosPersonalizados {
            get {
                return ResourceManager.GetString("PedidosPersonalizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil del artesano próximamente.
        /// </summary>
        public static string PerfilArtesanoProximamente {
            get {
                return ResourceManager.GetString("PerfilArtesanoProximamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string PlaceholderConfirmarContrasena {
            get {
                return ResourceManager.GetString("PlaceholderConfirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña nueva.
        /// </summary>
        public static string PlaceholderContrasenaNueva {
            get {
                return ResourceManager.GetString("PlaceholderContrasenaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plataforma académica de artesanos y clientes.
        /// </summary>
        public static string PlataformaAcademica {
            get {
                return ResourceManager.GetString("PlataformaAcademica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plataforma académica de artesanos y clientes.
        /// </summary>
        public static string PlataformaArtesanos {
            get {
                return ResourceManager.GetString("PlataformaArtesanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor esperá....
        /// </summary>
        public static string PorFavorEspera {
            get {
                return ResourceManager.GetString("PorFavorEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por la venta de:.
        /// </summary>
        public static string PorLaVentaDe {
            get {
                return ResourceManager.GetString("PorLaVentaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio máx..
        /// </summary>
        public static string PrecioMax {
            get {
                return ResourceManager.GetString("PrecioMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio mín..
        /// </summary>
        public static string PrecioMin {
            get {
                return ResourceManager.GetString("PrecioMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio unitario.
        /// </summary>
        public static string PrecioUnitario {
            get {
                return ResourceManager.GetString("PrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando....
        /// </summary>
        public static string Procesando {
            get {
                return ResourceManager.GetString("Procesando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos hechos a mano por artesanos locales.
        /// </summary>
        public static string ProductosHechosAMano {
            get {
                return ResourceManager.GetString("ProductosHechosAMano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este producto no tiene fotos adicionales.
        /// </summary>
        public static string ProductoSinFotosAdicionales {
            get {
                return ResourceManager.GetString("ProductoSinFotosAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos más vendidos.
        /// </summary>
        public static string ProductosMasVendidos {
            get {
                return ResourceManager.GetString("ProductosMasVendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto académico.
        /// </summary>
        public static string ProyectoAcademico {
            get {
                return ResourceManager.GetString("ProyectoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto Integrador.
        /// </summary>
        public static string ProyectoIntegrador {
            get {
                return ResourceManager.GetString("ProyectoIntegrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar de favoritos.
        /// </summary>
        public static string QuitarFavorito {
            get {
                return ResourceManager.GetString("QuitarFavorito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        public static string ReenviarCodigo {
            get {
                return ResourceManager.GetString("ReenviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string Registrarme {
            get {
                return ResourceManager.GetString("Registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        public static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita la contraseña.
        /// </summary>
        public static string RepetirContrasena {
            get {
                return ResourceManager.GetString("RepetirContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar a este artesano.
        /// </summary>
        public static string ReportarArtesano {
            get {
                return ResourceManager.GetString("ReportarArtesano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar artesano.
        /// </summary>
        public static string ReportarArtesanoBoton {
            get {
                return ResourceManager.GetString("ReportarArtesanoBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar este producto.
        /// </summary>
        public static string ReportarProducto {
            get {
                return ResourceManager.GetString("ReportarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reseñas.
        /// </summary>
        public static string Reseñas {
            get {
                return ResourceManager.GetString("Reseñas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de compra.
        /// </summary>
        public static string ResumenCompra {
            get {
                return ResourceManager.GetString("ResumenCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen informativo de ventas.
        /// </summary>
        public static string ResumenVentas {
            get {
                return ResourceManager.GetString("ResumenVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisá la carpeta de spam.
        /// </summary>
        public static string RevisarSpam {
            get {
                return ResourceManager.GetString("RevisarSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguir.
        /// </summary>
        public static string Seguir {
            get {
                return ResourceManager.GetString("Seguir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar foto.
        /// </summary>
        public static string SeleccionarFoto {
            get {
                return ResourceManager.GetString("SeleccionarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una categoría.
        /// </summary>
        public static string SeleccioneCategoria {
            get {
                return ResourceManager.GetString("SeleccioneCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una subcategoría.
        /// </summary>
        public static string SeleccioneSubcategoria {
            get {
                return ResourceManager.GetString("SeleccioneSubcategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin cliente.
        /// </summary>
        public static string SinCliente {
            get {
                return ResourceManager.GetString("SinCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no aceptaste ningún encargo..
        /// </summary>
        public static string SinEncargosAceptados {
            get {
                return ResourceManager.GetString("SinEncargosAceptados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin imagen.
        /// </summary>
        public static string SinImagen {
            get {
                return ResourceManager.GetString("SinImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay pedidos disponibles en este momento..
        /// </summary>
        public static string SinPedidosDisponibles {
            get {
                return ResourceManager.GetString("SinPedidosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin stock.
        /// </summary>
        public static string SinStock {
            get {
                return ResourceManager.GetString("SinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tenés ventas registradas todavía..
        /// </summary>
        public static string SinVentas {
            get {
                return ResourceManager.GetString("SinVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        public static string Soporte {
            get {
                return ResourceManager.GetString("Soporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soy artesano.
        /// </summary>
        public static string SoyArtesano {
            get {
                return ResourceManager.GetString("SoyArtesano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock disponible.
        /// </summary>
        public static string StockDisponible {
            get {
                return ResourceManager.GetString("StockDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubCategoria.
        /// </summary>
        public static string SubCategoria {
            get {
                return ResourceManager.GetString("SubCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subcategorías.
        /// </summary>
        public static string Subcategorias {
            get {
                return ResourceManager.GetString("Subcategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        public static string Subir {
            get {
                return ResourceManager.GetString("Subir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a También te puede interesar.
        /// </summary>
        public static string TambienTePuedeInteresar {
            get {
                return ResourceManager.GetString("TambienTePuedeInteresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta factura muestra únicamente datos relacionados a su compra. Es realizada a modo de prueba..
        /// </summary>
        public static string TextoFacturaNoFiscal {
            get {
                return ResourceManager.GetString("TextoFacturaNoFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este apartado muestra únicamente datos relacionados a sus ventas..
        /// </summary>
        public static string TextoResumenVentas {
            get {
                return ResourceManager.GetString("TextoResumenVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los productos.
        /// </summary>
        public static string TodosLosProductos {
            get {
                return ResourceManager.GetString("TodosLosProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total pagado.
        /// </summary>
        public static string TotalPagado {
            get {
                return ResourceManager.GetString("TotalPagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total vendido.
        /// </summary>
        public static string TotalVendido {
            get {
                return ResourceManager.GetString("TotalVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de ventas.
        /// </summary>
        public static string TotalVentas {
            get {
                return ResourceManager.GetString("TotalVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu apellido.
        /// </summary>
        public static string TuApellido {
            get {
                return ResourceManager.GetString("TuApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu nombre.
        /// </summary>
        public static string TuNombre {
            get {
                return ResourceManager.GetString("TuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus productos.
        /// </summary>
        public static string TusProductos {
            get {
                return ResourceManager.GetString("TusProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus ventas.
        /// </summary>
        public static string TusVentas {
            get {
                return ResourceManager.GetString("TusVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variación mensual.
        /// </summary>
        public static string VariacionMensual {
            get {
                return ResourceManager.GetString("VariacionMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendido por:.
        /// </summary>
        public static string VendidoPor {
            get {
                return ResourceManager.GetString("VendidoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta.
        /// </summary>
        public static string Venta {
            get {
                return ResourceManager.GetString("Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        public static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas del año.
        /// </summary>
        public static string VentasAño {
            get {
                return ResourceManager.GetString("VentasAño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas del mes.
        /// </summary>
        public static string VentasMes {
            get {
                return ResourceManager.GetString("VentasMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas por mes.
        /// </summary>
        public static string VentasPorMes {
            get {
                return ResourceManager.GetString("VentasPorMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver mi carrito.
        /// </summary>
        public static string VerCarrito {
            get {
                return ResourceManager.GetString("VerCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver catálogo.
        /// </summary>
        public static string VerCatalogo {
            get {
                return ResourceManager.GetString("VerCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalle.
        /// </summary>
        public static string VerDetalle {
            get {
                return ResourceManager.GetString("VerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles.
        /// </summary>
        public static string VerDetalles {
            get {
                return ResourceManager.GetString("VerDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación de correo.
        /// </summary>
        public static string VerificacionCorreo {
            get {
                return ResourceManager.GetString("VerificacionCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar código.
        /// </summary>
        public static string VerificarCodigo {
            get {
                return ResourceManager.GetString("VerificarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string VerPerfil {
            get {
                return ResourceManager.GetString("VerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al inicio.
        /// </summary>
        public static string VolverInicio {
            get {
                return ResourceManager.GetString("VolverInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la tienda.
        /// </summary>
        public static string VolverTienda {
            get {
                return ResourceManager.GetString("VolverTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tenés cuenta?.
        /// </summary>
        public static string YaTieneCuenta {
            get {
                return ResourceManager.GetString("YaTieneCuenta", resourceCulture);
            }
        }
    }
}
